---
?---
title: "Seurat_tutorial"
author: "Beatriz Val"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(Seurat)
library(patchwork)
library(presto)
library(ggplot2)
```

### **Load data**

```{r}
srat_hc <- readRDS("Hong2021_HC1_srat.RDS")
srat_hc@assays$RNA@counts[1:5,1:5]
```

\

```{r}
gene_rename_tab = data.frame("original" = rownames(srat_hc[["RNA"]]),
                               "new" = sapply(strsplit(rownames(srat_hc[["RNA"]]), "-"), 
                                              function(x) paste0(x[-1], collapse = "-")))
  gene_rename_tab$new[gene_rename_tab$new==""] = gene_rename_tab$original[gene_rename_tab$new==""]
  
  counts_gn = DelayedArray::rowsum(srat_hc[["RNA"]]@counts, group = gene_rename_tab$new)
  colnames(counts_gn) = colnames(srat_hc[["RNA"]])
  
  srat_hc = CreateSeuratObject(counts = counts_gn, meta.data = srat_hc@meta.data)
```

## Standard pre-processing workflow

### QC and selecting cells for further analysis

Compute mitochondrial QC metrics

```{r}
# The [[ operator can add columns to object metadata. This is a great place to stash QC stats
srat_hc[["percent.mt"]] <- PercentageFeatureSet(object = srat_hc, pattern = '^MT-')
head(srat_hc)
```

```{r}
# Visualize QC metrics as a violin plot
VlnPlot(srat_hc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

Cut-offs: 200, 2500 and 20

```{r}
# FeatureScatter is typically used to visualize feature-feature relationships, but can be used for anything calculated by the object, i.e. columns in object metadata, PC scores etc.

plot1 <- FeatureScatter(srat_hc, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(srat_hc, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2
```

```{r}
#srat_hc <- subset(srat_hc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
srat_hc <- srat_hc[,srat_hc$nFeature_RNA > 200 & srat_hc$nFeature_RNA < 2500 & srat_hc$percent.mt < 20]
```

```{r}
saveRDS(srat_hc, file = "srat_hc.rds")
```

## Normalizing the data

```{r}
srat_hc <- NormalizeData(srat_hc, normalization.method = "LogNormalize", scale.factor = 10000)
```

```{r}
srat_hc<- FindVariableFeatures(srat_hc, selection.method = "vst", nfeatures = 2000)

srat_hc$orig.ident
# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(srat_hc), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(srat_hc)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot1 + plot2
```

```{r}
all.genes <- rownames(srat_hc)
srat_hc <- ScaleData(srat_hc, features = all.genes)

```

```{r}
srat_hc <- RunPCA(srat_hc, features = VariableFeatures(object = srat_hc))
```

```{r}
# Examine and visualize PCA results a few different ways
print(srat_hc[["pca"]], dims = 1:5, nfeatures = 5)
```

```{r}
VizDimLoadings(srat_hc, dims = 1:2, reduction = "pca")
```

```{r}
DimPlot(srat_hc, reduction = "pca") + NoLegend()
```

```{r}
DimHeatmap(srat_hc, dims = 1, cells = 500, balanced = TRUE)
```

```{r}
DimHeatmap(srat_hc, dims = 1:15, cells = 500, balanced = TRUE)
```

```{r}
ElbowPlot(srat_hc, ndims = 50)
```

Cutoff - 15

```{r}
srat_hc <- FindNeighbors(srat_hc, dims = 1:15)
srat_hc <- FindClusters(srat_hc, resolution = 0.5)
head(Idents(srat_hc), 5)
```

## Run non-linear dimensional reduction (UMAP/tSNE)

```{r}
srat_hc <- RunUMAP(srat_hc, dims = 1:15)
# note that you can set `label = TRUE` or use the LabelClusters function to help label individual clusters
DimPlot(srat_hc, reduction = "umap")
```

```{r}
saveRDS(srat_hc, file = "umap.rds")
```

## Finding differentially expressed features (cluster biomarkers)

```{r}
# find all markers of cluster 2
cluster2.markers <- FindMarkers(srat_hc, ident.1 = 2)
head(cluster2.markers, n = 5)
```

```{r}
# find all markers distinguishing cluster 5 from clusters 0 and 3
cluster5.markers <- FindMarkers(srat_hc, ident.1 = 5, ident.2 = c(0, 3))
head(cluster5.markers, n = 5)
```

```{r}
# find markers for every cluster compared to all remaining cells, report only the positive
# ones
srat_hc.markers <- FindAllMarkers(srat_hc, only.pos = TRUE)
srat_hc.markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1)
```

```{r}
cluster0.markers <- FindMarkers(srat_hc, ident.1 = 0, logfc.threshold = 0.25, test.use = "roc", only.pos = TRUE)
```

```{r}
VlnPlot(srat_hc, features = c("MS4A1", "CD79A"))
```

```{r}
# you can plot raw counts as well
VlnPlot(srat_hc, features = c("NKG7", "PF4"), slot = "counts", log = TRUE)
```

```{r}
FeaturePlot(srat_hc, features = c("MS4A1", "GNLY", "CD3E", "CD14", "FCER1A", "FCGR3A", "LYZ", "PPBP",
    "CD8A"))
```

```{r}
srat_hc.markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1) %>%
    slice_head(n = 10) %>%
    ungroup() -> top10
DoHeatmap(srat_hc, features = top10$gene) + NoLegend()
```

```{r}
new.cluster.ids <- c("Naive CD4 T", "CD14+ Mono", "Memory CD4 T", "B", "CD8 T", "FCGR3A+ Mono", "NK", "DC", "Platelet", '9', '10')
names(new.cluster.ids) <- levels(srat_hc)
srat_hc <- RenameIdents(srat_hc, new.cluster.ids)
DimPlot(srat_hc, reduction = "umap", label = TRUE, pt.size = 0.5) + NoLegend()
```

```{r}
plot <- DimPlot(srat_hc, reduction = "umap", label = TRUE, label.size = 4.5) + xlab("UMAP 1") + ylab("UMAP 2") +
    theme(axis.title = element_text(size = 18), legend.text = element_text(size = 18)) + guides(colour = guide_legend(override.aes = list(size = 10)))
ggsave(filename = "srat_umap.jpg", height = 7, width = 12, plot = plot, quality = 50)
```

```{r}
saveRDS(srat_hc, file = "srat_hc_final.rds")
```
